using System.Text.Json.Serialization;

namespace SalesToSignature.Agents.Models;

/// <summary>A named work product with a description and due date.</summary>
public record Deliverable
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; init; } = string.Empty;

    [JsonPropertyName("dueDate")]
    public DateTime DueDate { get; init; }
}

/// <summary>A project milestone marking a significant checkpoint or phase completion.</summary>
public record Milestone
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; init; } = string.Empty;

    [JsonPropertyName("dueDate")]
    public DateTime DueDate { get; init; }
}

/// <summary>A single line item in the pricing breakdown (role × rate × hours = subtotal).</summary>
public record PricingLine
{
    [JsonPropertyName("role")]
    public string Role { get; init; } = string.Empty;

    [JsonPropertyName("rate")]
    public decimal Rate { get; init; }

    [JsonPropertyName("hours")]
    public int Hours { get; init; }

    [JsonPropertyName("subtotal")]
    public decimal Subtotal { get; init; }
}

/// <summary>
/// Statement of Work generated by the Proposal agent.
/// Built from SOW templates via <c>TemplateLookup</c> and priced via <c>PricingCalculator</c>.
/// </summary>
public record ProposalDocument
{
    [JsonPropertyName("executiveSummary")]
    public string ExecutiveSummary { get; init; } = string.Empty;

    [JsonPropertyName("scope")]
    public string Scope { get; init; } = string.Empty;

    [JsonPropertyName("deliverables")]
    public List<Deliverable> Deliverables { get; init; } = [];

    [JsonPropertyName("milestones")]
    public List<Milestone> Milestones { get; init; } = [];

    [JsonPropertyName("pricingBreakdown")]
    public List<PricingLine> PricingBreakdown { get; init; } = [];

    [JsonPropertyName("totalPrice")]
    public decimal TotalPrice { get; init; }

    [JsonPropertyName("engagementType")]
    public EngagementType EngagementType { get; init; }
}
